version: '3.5'

services:
  node_soup:
    container_name: BigLeap
    # image: "ubuntu_0721"
    # This could be a pre-built image from a Docker registry,
    # or it could be a local image you have already built.
    # If a Dockerfile is present and a build context is provided,
    # Docker Compose will build an image from the Dockerfile rather than 
    # pulling an image from a registry
    build:
      context: .
    volumes:
      - ./Complete_Example:/usr/code
    restart: "always"
    tty: true
    ports:
      - "5000:5000"
      - "6000-6020:6000-6020"
      - "7000:7000"
      - "8000-8020:8000-8020"
